# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-28 18:40
from __future__ import unicode_literals

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_album_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(upload_to='avatars'),
        ),
    ]
